name: Tests

on: [pull_request_target]

jobs:
  tests:
    name: Test contributors flow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        env:
          REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
          ENVIRONMENT_SECRET: ${{ secrets.ENVIRONMENT_SECRET }}
        run: |
          cat Buildfile
          echo "Repository secret: -- ${REPOSITORY_SECRET} --"
          echo "Environment secret: -- ${ENVIRONMENT_SECRET} --"
